FROM python:3.7

ENV PYTHONUNBUFFERED=1
RUN mkdir /code
WORKDIR /code

ADD requirements/prod.txt /code/
ADD requirements/common.txt /code/
RUN pip install -r prod.txt
ADD . /code/
RUN rm /code/crawler/settings/local.py

CMD ["celery", "-A", "crawler",  "worker", "--loglevel", "INFO", "-Q", "dev-crawler-download-video-file-queue"]

