# Generated by Django 3.0.6 on 2020-05-20 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name of project', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VideoSearchResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_link', models.URLField(help_text='Source vimeo/youtube link')),
                ('link', models.FileField(help_text='saved link to our storage', null=True, upload_to='')),
                ('preview_link', models.FileField(help_text='saved link for preveiw to our storage', null=True, upload_to='')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_search.VideoProject')),
            ],
        ),
    ]
