# Generated by Django 3.0.6 on 2020-05-31 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_search', '0003_auto_20200531_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosearchresult',
            name='video_title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
