# Generated by Django 3.0.6 on 2020-05-31 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_search', '0004_videosearchresult_video_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosearchresult',
            name='published_at',
            field=models.DateTimeField(null=True),
        ),
    ]
